// Code generated by goyacc -o y.go parser.y. DO NOT EDIT.

//line parser.y:2
package parser

import __yyfmt__ "fmt"

//line parser.y:2

//line parser.y:6
type yySymType struct {
	yys  int
	hint string
	val  any
}

const String = 57346
const Number = 57347
const Print = 57348
const Label = 57349
const Type = 57350
const Comment = 57351
const Get = 57352
const Put = 57353
const Post = 57354
const Delete = 57355
const Head = 57356
const Header = 57357
const Body = 57358
const Json = 57359

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"String",
	"Number",
	"Print",
	"Label",
	"Type",
	"Comment",
	"Get",
	"Put",
	"Post",
	"Delete",
	"Head",
	"Header",
	"Body",
	"Json",
	"'='",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"' '",
	"'('",
	"')'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 5,
	1, 10,
	9, 10,
	-2, 25,
	-1, 9,
	1, 8,
	9, 8,
	-2, 26,
}

const yyPrivate = 57344

const yyLast = 72

var yyAct = [...]int8{
	55, 47, 46, 13, 67, 40, 41, 54, 38, 53,
	24, 25, 26, 27, 65, 21, 22, 26, 27, 56,
	48, 33, 19, 20, 35, 34, 39, 23, 42, 43,
	44, 45, 49, 50, 51, 52, 19, 11, 5, 12,
	4, 14, 15, 16, 17, 18, 63, 66, 58, 57,
	59, 60, 61, 62, 19, 32, 35, 31, 30, 64,
	29, 28, 36, 9, 37, 10, 8, 7, 6, 3,
	2, 1,
}

var yyPact = [...]int16{
	31, 14, -1000, -1000, -1000, -3, -1000, -1000, -1000, -1000,
	-1000, -8, 20, -9, 57, 56, 54, 53, 51, -1000,
	-1000, 17, 1, -1000, 49, 49, 49, 49, 5, 5,
	5, 5, 5, -1000, -9, -1000, -1000, -16, -18, -1000,
	-1000, -1000, -4, -4, -1000, -1000, 3, 5, 44, 3,
	3, 3, 3, -1000, -1000, -1000, 42, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -10, 43, -21, -1000,
}

var yyPgo = [...]int8{
	0, 71, 70, 69, 68, 67, 66, 62, 65, 64,
	3, 1, 2, 0,
}

var yyR1 = [...]int8{
	0, 1, 1, 1, 1, 3, 3, 3, 3, 3,
	5, 9, 9, 4, 4, 4, 6, 2, 2, 2,
	7, 7, 7, 7, 10, 10, 10, 11, 12, 12,
	12, 13, 13, 13, 8, 8, 8, 8, 8,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 2, 1, 1, 1, 1, 1,
	1, 1, 1, 4, 4, 3, 2, 3, 3, 2,
	3, 3, 3, 3, 1, 1, 1, 2, 1, 0,
	2, 0, 2, 5, 4, 4, 4, 4, 4,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, 9, 7, -4, -5, -6, -7,
	-8, 6, 8, -10, 10, 11, 12, 13, 14, 5,
	9, 18, 24, 7, 19, 20, 21, 22, 4, 4,
	4, 4, 4, 4, -10, 7, -7, -9, 7, 25,
	4, 5, -10, -10, -10, -10, -12, -11, 15, -12,
	-12, -12, -12, 25, 25, -13, 16, -11, 4, -13,
	-13, -13, -13, 4, 17, 24, 4, 25,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, -2, 5, 6, 7, -2,
	9, 0, 0, 0, 0, 0, 0, 0, 0, 24,
	4, 19, 0, 16, 0, 0, 0, 0, 29, 29,
	29, 29, 29, 17, 18, 25, 26, 0, 0, 15,
	11, 12, 20, 21, 22, 23, 31, 28, 0, 31,
	31, 31, 31, 13, 14, 34, 0, 30, 27, 35,
	36, 37, 38, 32, 0, 0, 0, 33,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 23, 3, 3, 3, 3, 3, 3, 3,
	24, 25, 21, 19, 3, 20, 3, 22, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 18,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:43
		{
			PrintYySymDebug(yyDollar[1])
		}
	case 13:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:49
		{
			PrintYySym(yyDollar[3])
		}
	case 14:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:50
		{
			PrintGlobalYySym(yyDollar[3])
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:51
		{
			println("")
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:54
		{
			PrintType(yyDollar[2])
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:57
		{
			GlobalVarWrite(yyDollar[1], yyDollar[3].val)
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:58
		{
			GlobalVarWrite(yyDollar[1], yyDollar[3].val)
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:59
		{
			SyntaxError()
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:62
		{
			yyVAL = yySymType{val: ValAdd(yyDollar[1].val, yyDollar[3].val)}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:63
		{
			yyVAL = yySymType{val: ValMinus(yyDollar[1].val, yyDollar[3].val)}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:64
		{
			yyVAL = yySymType{val: ValMul(yyDollar[1].val, yyDollar[3].val)}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:65
		{
			yyVAL = yySymType{val: ValDiv(yyDollar[1].val, yyDollar[3].val)}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:68
		{
			yyVAL = yyDollar[1]
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:69
		{
			yyVAL = yySymType{val: GlobalVarRead(yyDollar[1])}
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:70
		{
			yyVAL = yyDollar[1]
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:73
		{
			yyVAL = yyDollar[2]
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:76
		{
			yyVAL = yyDollar[1]
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:78
		{
			yyVAL = joinHeaders(yyDollar[1], yyDollar[2])
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:82
		{
			yyVAL = yySymType{val: yyDollar[2].val, hint: "text"}
		}
	case 33:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:83
		{
			yyVAL = yySymType{val: yyDollar[4].val, hint: "json"}
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:86
		{
			HttpSend("GET", yyDollar[2].val.(string), yyDollar[3], yyDollar[4])
		}
	case 35:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:87
		{
			HttpSend("PUT", yyDollar[2].val.(string), yyDollar[3], yyDollar[4])
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:88
		{
			HttpSend("POST", yyDollar[2].val.(string), yyDollar[3], yyDollar[4])
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:89
		{
			HttpSend("DELETE", yyDollar[2].val.(string), yyDollar[3], yyDollar[4])
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:90
		{
			HttpSend("HEAD", yyDollar[2].val.(string), yyDollar[3], yyDollar[4])
		}
	}
	goto yystack /* stack new state and value */
}
